# Generated by Django 3.1.5 on 2021-04-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_name', models.CharField(blank=True, max_length=100)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
                ('comment', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('H_name', models.CharField(blank=True, max_length=100)),
                ('rent', models.IntegerField(blank=True, default=0, null=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('H_status', models.CharField(blank=True, max_length=100)),
                ('Landlord_no', models.IntegerField(blank=True, default=0, null=True)),
                ('caretaker_no', models.IntegerField(blank=True, default=0, null=True)),
                ('favorite', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
