# Generated by Django 3.1.5 on 2021-04-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20210426_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='picture',
            field=models.ImageField(blank=True, default='IMG_20210418_160459_5.jpg', null=True, upload_to='images'),
        ),
    ]
