# Generated by Django 3.1.5 on 2021-04-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20210426_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='H_status',
        ),
        migrations.AddField(
            model_name='details',
            name='H_status',
            field=models.ManyToManyField(to='index.House'),
        ),
    ]
