# Generated by Django 3.1.5 on 2021-04-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20210428_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='details',
            old_name='User_name',
            new_name='user_name',
        ),
        migrations.RemoveField(
            model_name='details',
            name='H_status',
        ),
    ]
