# Generated by Django 3.1.5 on 2021-04-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20210428_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='status',
            field=models.ManyToManyField(blank=True, to='index.Condition'),
        ),
    ]
