# Generated by Django 3.1.5 on 2021-04-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_house_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='status',
        ),
        migrations.AddField(
            model_name='house',
            name='status',
            field=models.CharField(blank=True, choices=[('A', 'Self-contained'), ('B', 'Monthly Payment'), ('C', 'tiles floor'), ('', 'tiles floor'), ('D', 'Available hot shower'), ('E', 'deposit Payment')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Condition',
        ),
    ]
